language: java

notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/ALE3Q4HJE
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
